##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ezyitias/reeshu/projectgallery/portfolio
    - if [ -d "$DEPLOYPATH" ]; then echo "Deployment path exists."; else echo "Creating deployment path."; mkdir -p $DEPLOYPATH; fi
    - /bin/cp -R * $DEPLOYPATH || { echo "Copy failed"; exit 1; }
    - echo "Deployment completed successfully."
